### ISSUE TITLE
Purpose and target

### ISSUE THREAD

**Issue by jadbox** [celrenheit/sandglass#4]
I've been eyeing this project and wondering what the goal may be. Is it to be a Kafka alternative in Go? What market differentiator does this aim to be?

**Comment by celrenheit** [comment]
Hi Jonathan,

This is not meant to be a Kafka alternative although it borrows the same nomenclature (topic, partition, ...). Sandglass can/should be used in conjunction with Kafka (at the of the pipeline).

This project has two main goals:
* be able to consume from a partition and acknowledge each message individually
* be able to produce messages in order to be consumed in the future

The first goal allows to have multiple consumers per partition supporting this way the [competing consumers pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/competing-consumers). In Kafka, the unit of parallelism is the number of partitions. Now, what if you are willing to sacrifice ordering in favor of greater parallelism then Sandglass might be for you. For example triggering an http call to an unreliable server, sending emails, or whatever takes time.
Instead of registering where you arrived (commit offset), you acknowledge each one when it is done (underneat sandglass has a commit offset). This allows use cases where you trigger a large number of goroutines. An other thing, NACK (not acknowledged - not done yet) will allow to reschedule a message to another consumer immediately if something fails or the consumer version is too old for the payload, etc... 

The second goal is to be able to schedule message that can be consumed by consumers only in some future time. This allows Sandglass to be used as a task queue. Note that producing messages to be consumed in future loses ordering (besides time) as we can't know if a message produced at time T is happening before or after a message produced in the future to be consumed at time T (is this clear ?). However, you can group tasks together to be consumed in the future in order by generating a random [Sandflake WorkerID](https://godoc.org/github.com/celrenheit/sandflake#FixedTimeGenerator). (I have some ideas on how to solve this)
This is useful either for scheduling a task or for retrying a task using a delay. Handling cron job or recurring jobs at specific intervals is currently not a goal.

Hope this answers your questions. I'll close this issue for now, feel free to re-open it if something wasn't clear or if you have more questions :-)
